services:
  - type: web
    name: ichigo-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: bash start.sh
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    pullRequestPreviewsEnabled: false
